/**
 * ISOLATED SLIDE RENDERER — iframe.js
 * ─────────────────────────────────────
 * Renders slide HTML into a sandboxed iframe.
 *
 * KEY DESIGN DECISIONS:
 *   1. App CSS NEVER enters the slide iframe.
 *   2. Slide CSS NEVER leaks into the app.
 *   3. Scripts are sandboxed (allow-scripts only, no allow-same-origin).
 *   4. Streamed HTML is buffered — not injected token-by-token.
 *   5. Slide scales to fit the iframe via a JS scaler injected into srcdoc.
 *
 * THREE-LAYER CSS ARCHITECTURE:
 *   Layer 1: App CSS (style.css)          → app UI only, never touches slides
 *   Layer 2: Deck theme CSS (themes/*.css) → injected into each slide iframe
 *   Layer 3: Per-slide scoped CSS          → generated by LLM inside <section>
 */

// ── Buffer state for streaming ────────────────────────────────────────────────
const _buffers = new Map(); // iframeId → { chunks: string[], pending: bool }

/**
 * Get or create a buffer for an iframe.
 */
function _getBuffer(iframeId) {
  if (!_buffers.has(iframeId)) {
    _buffers.set(iframeId, { chunks: [], pending: false, accumulated: '' });
  }
  return _buffers.get(iframeId);
}

// ── Core: Render full HTML into iframe ────────────────────────────────────────
/**
 * Render complete slide HTML into a target iframe.
 * Wraps in a full document with theme CSS and scaler script.
 *
 * @param {HTMLIFrameElement} iframe - target iframe element
 * @param {string} html - the <section class="slide"> HTML from LLM
 * @param {string} theme - theme name, e.g. 'dark-tech'
 */
export function renderSlideInIframe(iframe, html, theme = 'dark-tech') {
  if (!iframe) return;
  iframe.srcdoc = buildSlideDocument(html, theme);
}

/**
 * Build a complete standalone HTML document for a slide.
 * This is the document that lives INSIDE the iframe.
 */
export function buildSlideDocument(slideHtml, theme = 'dark-tech') {
  // Strip markdown fences that LLMs sometimes emit
  const cleanHtml = _stripMarkdownFences(slideHtml);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- LAYER 2: Deck Theme CSS — defines CSS variables for the slide -->
  <link rel="stylesheet" href="/themes/${theme}.css">

  <!-- Prism.js for code highlighting (if slide has code blocks) -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/themes/prism-tomorrow.min.css">

  <style>
    /* Slide container reset — no app styles here */
    *, *::before, *::after { box-sizing: border-box; }
    html, body {
      margin: 0;
      padding: 0;
      width: 100%;
      height: 100%;
      overflow: hidden;
    }
    /* Scaler wrapper */
    #slide-scaler {
      transform-origin: top left;
      position: absolute;
      top: 0;
      left: 0;
    }
    /* Reveal animation support */
    .reveal {
      opacity: 0;
      transform: translateY(20px);
      transition: opacity 0.5s cubic-bezier(0.16,1,0.3,1), transform 0.5s cubic-bezier(0.16,1,0.3,1);
      transition-delay: var(--delay, 0s);
    }
    .reveal.visible {
      opacity: 1;
      transform: translateY(0);
    }
  </style>
</head>
<body>
  <div id="slide-scaler">
    <!-- LAYER 3: Per-slide scoped CSS is inside the LLM-generated <section> -->
    ${cleanHtml}
  </div>

  <!-- Prism.js for syntax highlighting -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/prism.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/components/prism-javascript.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/components/prism-python.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.29.0/components/prism-typescript.min.js"></script>

  <script>
    // ── Slide Scaler ──────────────────────────────────────────────────────────
    // Scales the slide content to fit the iframe without overflow.
    function fitSlide() {
      const scaler = document.getElementById('slide-scaler');
      if (!scaler) return;
      const slide = scaler.firstElementChild;
      if (!slide) return;

      // Measure natural size
      const naturalW = slide.scrollWidth || slide.offsetWidth || 1280;
      const naturalH = slide.scrollHeight || slide.offsetHeight || 720;

      const scaleX = window.innerWidth / naturalW;
      const scaleY = window.innerHeight / naturalH;
      const scale = Math.min(scaleX, scaleY);

      scaler.style.transform = 'scale(' + scale + ')';

      // Center the scaled slide
      const scaledW = naturalW * scale;
      const scaledH = naturalH * scale;
      scaler.style.marginLeft = ((window.innerWidth - scaledW) / 2) + 'px';
      scaler.style.marginTop = ((window.innerHeight - scaledH) / 2) + 'px';
    }

    // ── Reveal animations ─────────────────────────────────────────────────────
    function triggerReveal() {
      document.querySelectorAll('.reveal').forEach(el => {
        el.classList.add('visible');
      });
    }

    // ── Initialize ────────────────────────────────────────────────────────────
    window.addEventListener('load', () => {
      fitSlide();
      setTimeout(triggerReveal, 100);
    });
    window.addEventListener('resize', fitSlide);

    // Run immediately if already loaded
    if (document.readyState === 'complete') {
      fitSlide();
      setTimeout(triggerReveal, 100);
    }
  </script>
</body>
</html>`;
}

// ── Streaming: buffer tokens, patch iframe periodically ───────────────────────
/**
 * Called for each streamed token during slide generation.
 * Accumulates tokens and patches the iframe at a controlled rate.
 *
 * @param {HTMLIFrameElement} iframe - target iframe
 * @param {string} token - new token from SSE stream
 * @param {string} theme - current theme
 * @param {string} iframeId - unique ID for this iframe's buffer
 */
export function appendStreamToken(iframe, token, theme = 'dark-tech', iframeId = 'main') {
  const buf = _getBuffer(iframeId);
  buf.accumulated += token;

  // Throttle: update at most every 200ms to avoid thrashing the DOM
  if (!buf.pending) {
    buf.pending = true;
    setTimeout(() => {
      _patchIframe(iframe, buf.accumulated, theme);
      buf.pending = false;
    }, 200);
  }
}

/**
 * Called when the stream is complete. Forces a final render.
 *
 * @param {HTMLIFrameElement} iframe
 * @param {string} theme
 * @param {string} iframeId
 */
export function finalizeStream(iframe, theme = 'dark-tech', iframeId = 'main') {
  const buf = _getBuffer(iframeId);
  buf.pending = false; // cancel any pending update
  if (buf.accumulated) {
    _patchIframe(iframe, buf.accumulated, theme);
  }
  // Clear buffer for this iframe
  _buffers.delete(iframeId);
}

/**
 * Reset/clear an iframe's stream buffer.
 */
export function clearStreamBuffer(iframeId = 'main') {
  _buffers.delete(iframeId);
}

// ── Internal: patch iframe srcdoc ────────────────────────────────────────────
function _patchIframe(iframe, html, theme) {
  if (!iframe || !html?.trim()) return;

  // Only render if we have at least a partial section tag
  // This prevents flashing on the very first tokens
  if (!html.includes('<section') && !html.includes('<div') && !html.includes('<style')) {
    return; // Too early — wait for more content
  }

  iframe.srcdoc = buildSlideDocument(html, theme);
}

// ── Utilities ─────────────────────────────────────────────────────────────────
/**
 * Strip markdown code fences that LLMs occasionally emit.
 * Handles: ```html\n...\n``` and ```\n...\n```
 */
export function _stripMarkdownFences(text) {
  if (!text) return '';
  text = text.trim();

  // Opening fence: ```html or ``` followed by newline
  if (text.startsWith('```')) {
    const firstNewline = text.indexOf('\n');
    if (firstNewline !== -1) {
      text = text.slice(firstNewline + 1);
    } else {
      text = text.slice(3);
    }
  }

  // Closing fence
  if (text.endsWith('```')) {
    text = text.slice(0, text.lastIndexOf('```'));
  }

  return text.trim();
}

/**
 * Validate that LLM output looks like a real slide.
 */
export function validateSlideHtml(html) {
  if (!html || typeof html !== 'string') return false;
  return html.includes('<section') && html.includes('slide');
}

/**
 * Render a placeholder slide (used while generating or on error).
 */
export function renderPlaceholderInIframe(iframe, message = 'Loading...') {
  if (!iframe) return;
  iframe.srcdoc = `<!DOCTYPE html>
<html>
<head>
  <style>
    body {
      background: #000;
      color: #444;
      display: flex;
      align-items: center;
      justify-content: center;
      height: 100vh;
      margin: 0;
      font-family: system-ui, sans-serif;
      font-size: 0.8rem;
      text-transform: uppercase;
      letter-spacing: 0.15em;
    }
    .msg {
      border: 1px dashed #222;
      padding: 32px 48px;
      border-radius: 4px;
      text-align: center;
    }
  </style>
</head>
<body>
  <div class="msg">${message}</div>
</body>
</html>`;
}
